id: I234B4AF2
legacy_id: P007872
ocr_import_info:
  bdrc_scan_id: W1PD76622
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T01:42:10'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T04:57:01.162748+00:00'
last_modified: 2022-09-01 12:57:31.797679
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1PD76622
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1PD76622
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མཛོད་དགེའི་དགོན་སྡེའི་ལོ་རྒྱུས་མདོར་བསྡུས།
statistics:
  ocr_word_mean_confidence_index: 0.8571527246889566
  ocr_word_median_confidence_index: 0.9100000262260437
quality: null
bases:
  I1PD93190:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD93190
      total_pages: 572
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD93190.txt
    statistics:
      ocr_word_median_confidence_index: 0.9100000262260437
      ocr_word_mean_confidence_index: 0.8571527246889566
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
