id: I234B4AF2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T01:46:01+00:00'
last_modified: '2022-06-09T06:52:40.069209+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD76622
  title: མཛོད་དགེའི་དགོན་སྡེའི་ལོ་རྒྱུས་མདོར་བསྡུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    33A3:
      image_group_id: I1PD93190
      title: Volume 1 of
      total_pages: 572
      order: 1
      base_file: 33A3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
