id: P007872
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD76622
  title: མཛོད་དགེའི་དགོན་སྡེའི་ལོ་རྒྱུས་མདོར་བསྡུས
  author: ''
  volumes:
    e2d01f652c234fd58c3799b9491cc560:
      image_group_id: I1PD93190
      title: ''
      volume_number: 1
      total_pages: 572
ebook_metadata:
  title: མཛོད་དགེའི་དགོན་སྡེའི་ལོ་རྒྱུས་མདོར་བསྡུས
  author: ''
  sku: P007872
  cover: cover.jpg
  layers:
  - pagination
