id: P007872
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD76622
  title: མཛོད་དགེའི་དགོན་སྡེའི་ལོ་རྒྱུས་མདོར་བསྡུས
  author: ''
  volumes:
    d17b5ea2598d4dc9afbd10c9e3043c92:
      image_group_id: I1PD93190
      title: Volume 1 of
      volume_number: 1
      total_pages: 572
      base_file: v001.txt
ebook_metadata:
  title: མཛོད་དགེའི་དགོན་སྡེའི་ལོ་རྒྱུས་མདོར་བསྡུས
  author: ''
  sku: P007872
  cover: cover.jpg
  layers:
  - pagination
